title: OrionTheStarhog
description: Gamer, streamer, professional screamer, all the things you'd expect out of someone competitive.
color: 00ff00

discord: https://discord.gg/pDURY5V
youtube: https://www.youtube.com/channel/UCXL-FoahKmR-wdGdv2fXOeQ
twitter: https://twitter.com/OrionTheStarhog
